### ISSUE TITLE
NetfilterQueue not installing

### ISSUE THREAD

**Issue by riddhiman1** [oremanj/python-netfilterqueue#69] opened 2021-08-06 07:20 UTC
I have tried all of the listed methods,
**Cloning into 'python-netfilterqueue'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
**
Guys you need to update, now it is python 3.9 . Please do something it is urgent.

**Comment by winterrdog** [comment] 2021-08-07 18:13
I am experiencing the same issue with python3.9
I don't know why it is happening. This is the reason i see in the traceback, it maybe that a certain C header file is missing:
**netfilterqueue.c:437:10: fatal error: libnfnetlink/linux_nfnetlink.h: No such file or directory
    437 | #include "libnfnetlink/linux_nfnetlink.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for netfilterqueue**

This happened when i used "pip3 install netfilterqueue" to install it

**Comment by borisarloff** [comment] 2021-09-12 14:13
The problem is with CPython for Python 3.9 changes. PyTypeObject.tp_print was removed but not from the netfilterqueue.c file, hence it cannot compile crrectly under Python 3.9. You need to revert to Python 3.8 or patch the netfilterqueue.c file.

**Comment by oremanj** [comment] 2022-01-12 05:54
@winterrdog You need to install the libnetfilter_queue development headers. On Debian or Ubuntu this is `apt-get install libnetfilter-queue-dev`, not sure the appropriate package on other distros.

@borisarloff I just pushed an update that fixes compilation on 3.9 (and 3.10). It will be released to PyPI shortly.

@riddhiman1 The URL in the readme was outdated; I fixed it, try now. `https://github.com/oremanj/python-netfilterqueue`

**Closed by oremanj** 2022-01-12 05:54 UTC
